#!/usr/bin/env python
#Report Status Bumper Turtlebot3 
#Autor: Licia Sales


import RPi.GPIO as GPIO
import time
import rospy
from std_msgs.msg import UInt8

pub = None
bumpis=0000
bump1=26
bump2=16
bump3=20
bump4=21
GPIO.setmode(GPIO.BCM)
GPIO.setup(bump1, GPIO.IN, pull_up_down=GPIO.PUD_UP)
GPIO.setup(bump2, GPIO.IN, pull_up_down=GPIO.PUD_UP)
GPIO.setup(bump3, GPIO.IN, pull_up_down=GPIO.PUD_UP)
GPIO.setup(bump4, GPIO.IN, pull_up_down=GPIO.PUD_UP)
lpid = 0

class LatchPublisher(rospy.Publisher, rospy.SubscribeListener):
    def __init__(self, name, data_class, tcp_nodelay=False, headers=None, queue_size=None):
        global lpid
        self.id = lpid
        lpid += 1
        print("Created LatchPublisher %d %s" % (self.id, name))
        super(LatchPublisher, self).__init__(name, data_class=data_class, tcp_nodelay=tcp_nodelay, headers=headers, queue_size=queue_size, subscriber_listener=self, latch=False)
        self.message = None

    def publish(self, msg):
        print("Publishing message %d" % self.id)
        self.message = msg
        super(LatchPublisher, self).publish(msg)

    def peer_subscribe(self, resolved_name, publish, publish_single):
        print("A subscriber attached to %d %s" % (self.id, resolved_name))
        if self.message is not None:
            print("  Publishing 'latched' message %d" % self.id)
            publish_single(self.message)
            print("  Published 'latched' message %d" % self.id)

def interrupt(channel):
    if channel == bump1:
      	bumpis=1
        pub.publish(UInt8(bumpis))
    if channel == bump2:
      	bumpis=2
        pub.publish(UInt8(bumpis))
    if channel == bump3:
        bumpis=3
        print(bumpis)
        pub.publish(UInt8(bumpis))
    if channel == bump4:
        bumpis=4 
        print(bumpis)
        pub.publish(UInt8(bumpis))

GPIO.add_event_detect(bump1, GPIO.RISING, callback=interrupt, bouncetime=1000)
GPIO.add_event_detect(bump2, GPIO.RISING, callback=interrupt, bouncetime=1000)
GPIO.add_event_detect(bump3,GPIO.RISING, callback=interrupt, bouncetime=1000)
GPIO.add_event_detect(bump4, GPIO.RISING, callback=interrupt, bouncetime=1000)


rospy.init_node('bumper')
pub = LatchPublisher("bumper", UInt8, queue_size=10)
rospy.spin()
GPIO.cleanup()
